### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

### ISSUE THREAD

**Issue by WFKMSX** [MushroomRL/mushroom-rl#137] opened 2023-12-22 06:05 UTC
python3.10/site-packages/mushroom_rl/approximators/parametric/torch_approximator.py"

        if not self._use_cuda:
            torch_args = [torch.as_tensor(x) if isinstance(x, np.ndarray) else x
                          for x in args]
            val = self.network(*torch_args, **kwargs)

torch_args = [torch.as_tensor(x) if isinstance(x, np.ndarray) else x
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by boris-il-forte** [comment] 2023-12-23 14:52
This is not a bug, per se. The behavior and the error are totally fine: you cannot pass an object as an input to the NN.
The question is: why are you passing an np.ndarray of type numpy.object_ to the network?

**Comment by boris-il-forte** [comment] 2024-02-05 11:47
Closing due to lack of further response on this issue.

**Closed as completed by boris-il-forte** 2024-02-05 11:47 UTC
